### ISSUE TITLE
OpenWhispr 1.7.4 breaks GNOME Wayland global hotkey and tray icon due to D-Bus crash

### ISSUE THREAD

**Issue by LucDub-code** [OpenWhispr/openwhispr#1107]
After upgrading OpenWhispr from 1.7.3 to 1.7.4 on Ubuntu GNOME Wayland, the global dictation hotkey no longer works outside the OpenWhispr window.

Symptoms:
- OpenWhispr starts automatically
- The dictation shortcut works only when the OpenWhispr window is focused
- The global shortcut does not work in other apps
- The tray icon is missing after startup
- Downgrading back to 1.7.3 fixes the issue

Environment:
- Ubuntu 26.04 LTS
- GNOME 50
- Wayland
- OpenWhispr 1.7.4: broken
- OpenWhispr 1.7.3: works

Relevant logs:

Uncaught Exception: TypeError: util.isError is not a function
    at USocket._write (/opt/OpenWhispr/resources/app.asar/node_modules/usocket/index.js:64:11)
    at auth (/opt/OpenWhispr/resources/app.asar/node_modules/dbus-next/lib/handshake.js:67:10)

This appears to break the GNOME/D-Bus integration used for global shortcuts and tray behavior.

**Comment by benjuliano1** [comment]
I have the same issue.

**Comment by AlexZKR** [comment]
Confirming this on an independent setup — same root cause, with some extra evidence.

I initially assumed something was broken on my own system and spent a while troubleshooting with Claude Code, but it turns out the problem is entirely in the 1.7.4 build, not my machine. I ended up having to downgrade to 1.7.3, unfortunately.

**Environment**
- Ubuntu (GNOME `ubuntu:GNOME`, `XDG_SESSION_TYPE=wayland`)
- OpenWhispr **1.7.4**, bundled **Electron 41.10.0**
- Symptoms reproduced exactly: dictation hotkey only fires when an OpenWhispr window has focus; tray icon never appears.

**Root cause (confirmed from the running app's stderr)**
```
Uncaught Exception: TypeError: util.isError is not a function
    at auth (/opt/OpenWhispr/resources/app.asar/node_modules/dbus-next/lib/handshake.js:67:10)
    at USocket.<anonymous> (/opt/OpenWhispr/resources/app.asar/node_modules/dbus-next/lib/connection.js:138:34)
```
`util.isError()` is one of the legacy `util.is*` type-checkers that has been removed from the Node runtime shipped in Electron 41. `dbus-next`'s SASL handshake still calls it, so the session-bus connection throws before the service name is claimed.

**Why that kills the hotkey + tray (traced through the 1.7.4 bundle)**
- `src/helpers/gnomeShortcut.js` → `initDBusService()` calls `bus.requestName("com.openwhispr.App")` and exports a `Toggle` method; the GNOME keybinding it writes runs `dbus-send … com.openwhispr.App.Toggle`.
- Because the handshake throws, that D-Bus name is never owned. On my machine `busctl --user list` / `gdbus` show **`com.openwhispr.App` is owned by no process**, and `gsettings` has **no `openwhispr` custom keybinding** (only a leftover empty `openwhispr-meeting` entry).
- `src/helpers/hotkeyManager.js` then hits its documented fallback (`"GNOME keybinding failed, falling back to globalShortcut"`), and Electron `globalShortcut`/XGrabKey is focus-only under Wayland — hence the exact symptom.

**Workaround confirmed:** downgrading to **1.7.3** restores background hotkey + tray.

**Suggested fix:** stop relying on the removed `util.isError` in the D-Bus path — bump `dbus-next` to a release that doesn't use it, or shim it (`util.isError = e => e instanceof Error`) before the bus connects.

**Possibly related:** on 1.7.4 the in-app updater repeatedly re-stages and reinstalls the *same* 1.7.4 (a `draft` release per `app-update.yml`) via `pkexec dpkg`, restarting the app in a loop — which also matches reports of the update "freezing" on quit.

**Comment by andrewkobzev** [comment]
Another affected user, and a caution about the suggested fix.

**Environment:** Ubuntu 26.04 LTS, GNOME 50 (`ubuntu:GNOME`, `XDG_SESSION_TYPE=wayland`), OpenWhispr **1.7.4**, bundled **Electron 41.10.0 / Node 24.18.0 / Chromium 146**. `dbus-next@0.10.2`, `usocket@0.3.0`. Same symptoms exactly (dictation hotkey focus-only, no tray, `com.openwhispr.App` owned by nobody, no `openwhispr` gsettings keybinding).

**Heads-up: shimming `util.isError` alone is NOT sufficient.** I edited `usocket/index.js:64` `util.isError(r)` → `r instanceof Error` (semantically the same as the proposed `util.isError = e => e instanceof Error` shim). The original JS crash goes away — but the app then dies with a **native SIGTRAP (`code=dumped status=5/TRAP`) ~2 s after startup**, right where the D-Bus handshake now proceeds past the old throw point. Reverting the one-line change brings the app back (running, but degraded as described).

Clean discriminator, launch method held constant (reproduced under both the normal GNOME `app-gnome-open-whispr` scope and `systemd-run --user`):
- patched (util.isError callable) → SIGTRAP on every launch
- unpatched → runs (dbus dead, no tray/hotkeys)

So making `util.isError` callable is necessary but not sufficient — something further along the `dbus-next`/`usocket` connect path also fails under Electron 41 (`usocket@0.3.0` is unmaintained and ships a native fd-passing addon — prime suspect). Please verify a shimmed build actually stays up on Electron 41 before shipping; it may need `usocket`/`dbus-next` replaced or the whole D-Bus shortcut path guarded/reworked on this runtime. Downgrade to 1.7.3 confirmed as the working workaround.

**Comment by yusufipk** [comment]
I have the same issue with KDE on CachyOS

**Comment by gabrielste1n** [comment]
should be resolved in v1.7.5 - please let me know if it still persists :)

**Comment by loks1234** [comment]
v1.7.5 did resolve this issue for me on kde cachyos. Now the tray icon and Global shortcuts do work normally. Thank You @gabrielste1n .

**Comment by LucDub-code** [comment]
I updated to version 1.7.5 and can confirm that the issue is fixed on Ubuntu 26.04 with GNOME Wayland.
The global shortcut now works outside the OpenWhispr window, and the tray icon is present after startup.
Thank you for the fix! I’m closing the issue.
